services:
  deb-builder:
    build:
      context: .
      dockerfile: Dockerfile-ubuntu
    image: jpackage:nonmodular-ubuntu
    volumes:
      - '.:/home/ubuntu/project'
  rpm-builder:
    build:
      context: .
      dockerfile: Dockerfile-ubi
    image: jpackage:nonmodular-ubi
    volumes:
      - '.:/home/builder/project'
