FROM eclipse-temurin:21.0.6_7-jdk-noble

RUN apt-get update && apt install -y fakeroot make

USER ubuntu:ubuntu

RUN mkdir -p /home/ubuntu/project
WORKDIR /home/ubuntu/project

COPY --chown=ubuntu:ubuntu ./Makefile /home/ubuntu/project

CMD [ "make", "deb" ]
